### ISSUE TITLE
[PE-D] Edit email suggestion

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T12-3/tp#166]
Good to see that the team has implemented preventive measures to remind the users from entering the wrong email format. However, I feel that it is a bit hard to read all the reminders in the result display box since it is quite small and cramped.

You could use wrap-text = "true", try a smaller font size, or enlarge the result display panel to improve.

![image.png](https://raw.githubusercontent.com/Timothyoung97/ped/main/files/c7097d14-ce1c-48ba-804d-110c28575b24.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Timothyoung97/ped#6

**Comment by YaleChen299** [comment]
UI result display
