### ISSUE TITLE
[PE-D] No error message if start date before end date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T12-3/tp#169]
`addApp id/1 a/Starbucks @ Raffles City start/01-01-2000 1400 end/01-01-1999 1500 ds/discuss marketing strategies` for example. Pressing enter does nothing.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: koh-jx/ped#5

**Comment by YaleChen299** [comment]
same as #175
