### ISSUE TITLE
[PE-D] Wrong error message with invalid datetime

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T12-3/tp#179]
When the DateTime is invalid but with a correct format, the error message is still warning about the format.
![image.png](https://raw.githubusercontent.com/Ruofan1023/ped/main/files/6faa0a70-bd11-452d-b9bb-dfdf6ce6b0ce.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Ruofan1023/ped#10

**Comment by YaleChen299** [comment]
update both the UG and the code.
